package com.liberty.system.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKline<T extends BaseKline> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Integer id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public T setDate(java.util.Date date) {
		set("date", date);
		return (T)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public T setMax(java.lang.Double max) {
		set("max", max);
		return (T)this;
	}
	
	public java.lang.Double getMax() {
		return getDouble("max");
	}

	public T setMin(java.lang.Double min) {
		set("min", min);
		return (T)this;
	}
	
	public java.lang.Double getMin() {
		return getDouble("min");
	}

	public T setCurrencyId(java.lang.Integer currencyId) {
		set("currencyId", currencyId);
		return (T)this;
	}
	
	public java.lang.Integer getCurrencyId() {
		return getInt("currencyId");
	}

	public T setStrokeId(java.lang.Integer strokeId) {
		set("strokeId", strokeId);
		return (T)this;
	}
	
	public java.lang.Integer getStrokeId() {
		return getInt("strokeId");
	}

}
