package com.liberty.system.model;

import java.util.List;
import java.util.Map;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.liberty.system.model.base.BaseKline;
import com.liberty.system.query.KlineQueryObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kline extends BaseKline<Kline> {
	public static final Kline dao = new Kline().dao();
	public Page<Kline> paginate(KlineQueryObject qo) {
		SqlPara sqlPara = getSqlParaFromTemplate(Kv.by("qo", qo));
		return dao.paginate(qo.getCurrentPage(), qo.getPageSize(), sqlPara);
	}
	
	public Kline getLastByCode(String code) {
		SqlPara sqlPara = getSqlParaFromTemplate(Kv.by("code", code));
		Kline kline = dao.findFirst(sqlPara);
		return kline;
	}
	
	public void saveMany(Map<String, List<Kline>> klineMap, Map<String, Kline> lastKlineMap){
		for (String code : klineMap.keySet()) {
			List<Kline> list = klineMap.get(code);
			Kline lastKline = lastKlineMap.get(code);
			if(lastKline==null){
				for (Kline kline : list) {
					kline.save();
				}
			}else{
				for (Kline kline : list) {
					if(kline.getDate().getTime()<lastKline.getDate().getTime()){
						continue;
					}
					kline.save();
				}
			}
		}
	}
}
