package com.liberty.system.model;

import com.liberty.system.model.base.BaseStrategy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Strategy extends BaseStrategy<Strategy>{
	public static final Strategy dao = new Strategy().dao();
	
}
